# Generated by Django 5.0.6 on 2026-07-11 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_STATUS_CHANGED', 'Order Status Changed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
