"""Static catalog definitions for the seed_data management command.

This module intentionally centralizes all catalog data so the command can stay
small and focused on orchestration while the catalog itself remains readable,
modular, and easy to extend.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path
from typing import Dict, List


@dataclass(frozen=True)
class ProductSeed:
    """A single product record to create during seeding."""

    name: str
    category: str
    brand: str
    price: Decimal
    image_paths: tuple[str, ...]
    description: str
    short_description: str


CATEGORY_NAMES: List[str] = [
    "Smartphones",
    "Laptops",
    "Audio Devices",
    "Computer Accessories",
    "Men's Fashion",
    "Women's Fashion",
    "Footwear",
    "Home & Kitchen",
    "Beauty & Personal Care",
    "Bags & Travel",
]

BRANDS: List[str] = [
    "Apple",
    "Samsung",
    "Google",
    "OnePlus",
    "Xiaomi",
    "Nothing",
    "Dell",
    "Lenovo",
    "HP",
    "ASUS",
    "Acer",
    "Sony",
    "JBL",
    "Bose",
    "Soundcore",
    "Marshall",
    "Logitech",
    "Anker",
    "TP-Link",
    "Nike",
    "Adidas",
    "Puma",
    "Levi's",
    "Tommy Hilfiger",
    "Allen Solly",
    "H&M",
    "Zara",
    "Only",
    "Vero Moda",
    "Biba",
    "Philips",
    "Nespresso",
    "Instant Pot",
    "Prestige",
    "LG",
    "CeraVe",
    "La Roche-Posay",
    "L'Oréal Paris",
    "Oral-B",
    "Nivea",
    "American Tourister",
    "Samsonite",
    "Wildcraft",
    "Skybags",
    "Clarks",
    "New Balance",
    "Skechers",
]

PRODUCTS: List[ProductSeed] = [
    ProductSeed(
        name="Apple iPhone 16 Pro",
        category="Smartphones",
        brand="Apple",
        price=Decimal("1199.00"),
        image_paths=("smartphones/apple_iphone_16_pro/front.jpg", "smartphones/apple_iphone_16_pro/gallery_1.jpg", "smartphones/apple_iphone_16_pro/gallery_2.jpg"),
        description="The Apple iPhone 16 Pro delivers flagship performance with a premium titanium build, advanced camera system, and all-day battery life.",
        short_description="Flagship smartphone with Pro camera upgrades and premium performance.",
    ),
    ProductSeed(
        name="Samsung Galaxy S25 Ultra",
        category="Smartphones",
        brand="Samsung",
        price=Decimal("1299.00"),
        image_paths=("smartphones/samsung_galaxy_s25_ultra/front.jpg", "smartphones/samsung_galaxy_s25_ultra/gallery_1.jpg", "smartphones/samsung_galaxy_s25_ultra/gallery_2.jpg"),
        description="The Samsung Galaxy S25 Ultra blends cutting-edge AI features, refined design, and a versatile photography system for power users.",
        short_description="Premium Android flagship with ultra-wide camera flexibility.",
    ),
    ProductSeed(
        name="Google Pixel 10",
        category="Smartphones",
        brand="Google",
        price=Decimal("899.00"),
        image_paths=("smartphones/google_pixel_10/front.jpg", "smartphones/google_pixel_10/gallery_1.jpg", "smartphones/google_pixel_10/gallery_2.jpg"),
        description="The Google Pixel 10 offers smooth Android performance, clean software, and exceptional photo processing tuned for everyday use.",
        short_description="AI-first smartphone with a refined camera experience.",
    ),
    ProductSeed(
        name="OnePlus 14",
        category="Smartphones",
        brand="OnePlus",
        price=Decimal("799.00"),
        image_paths=("smartphones/oneplus_14/front.jpg", "smartphones/oneplus_14/gallery_1.jpg", "smartphones/oneplus_14/gallery_2.jpg"),
        description="The OnePlus 14 focuses on fast performance, crisp displays, and efficient battery life at a competitive price point.",
        short_description="Performance-oriented smartphone with premium fluidity.",
    ),
    ProductSeed(
        name="Xiaomi 15",
        category="Smartphones",
        brand="Xiaomi",
        price=Decimal("749.00"),
        image_paths=("smartphones/xiaomi_15/front.jpg", "smartphones/xiaomi_15/gallery_1.jpg", "smartphones/xiaomi_15/gallery_2.jpg"),
        description="The Xiaomi 15 brings strong value, refined hardware, and dependable everyday performance in a sleek package.",
        short_description="Value-packed flagship with balanced performance and style.",
    ),
    ProductSeed(
        name="Nothing Phone (3)",
        category="Smartphones",
        brand="Nothing",
        price=Decimal("679.00"),
        image_paths=("smartphones/nothing_phone_3/front.jpg", "smartphones/nothing_phone_3/gallery_1.jpg", "smartphones/nothing_phone_3/gallery_2.jpg"),
        description="The Nothing Phone (3) stands out with its distinctive design and clean, software-first user experience.",
        short_description="Distinctive smartphone with a modern, transparent aesthetic.",
    ),
    ProductSeed(
        name="Apple MacBook Air M4",
        category="Laptops",
        brand="Apple",
        price=Decimal("1499.00"),
        image_paths=("laptops/apple_macbook_air_m4/front.jpg", "laptops/apple_macbook_air_m4/gallery_1.jpg"),
        description="The Apple MacBook Air M4 is a lightweight ultraportable built for productive work, travel, and all-day battery life.",
        short_description="Ultralight laptop with M4 power and outstanding battery life.",
    ),
    ProductSeed(
        name="Dell XPS 14",
        category="Laptops",
        brand="Dell",
        price=Decimal("1699.00"),
        image_paths=("laptops/dell_xps_14/front.jpg", "laptops/dell_xps_14/gallery_1.jpg"),
        description="The Dell XPS 14 pairs premium build quality with a vivid display and high-performance Intel-class processing.",
        short_description="Premium productivity laptop with a sleek, modern design.",
    ),
    ProductSeed(
        name="Lenovo ThinkPad X1 Carbon",
        category="Laptops",
        brand="Lenovo",
        price=Decimal("1799.00"),
        image_paths=("laptops/lenovo_thinkpad_x1_carbon/front.jpg", "laptops/lenovo_thinkpad_x1_carbon/gallery_1.jpg"),
        description="The Lenovo ThinkPad X1 Carbon is a business-first laptop renowned for its lightweight chassis and dependable performance.",
        short_description="Business laptop balancing portability, durability, and speed.",
    ),
    ProductSeed(
        name="HP Spectre x360",
        category="Laptops",
        brand="HP",
        price=Decimal("1549.00"),
        image_paths=("laptops/hp_spectre_x360/front.jpg", "laptops/hp_spectre_x360/gallery_1.jpg"),
        description="The HP Spectre x360 offers a convertible design, elegant finish, and strong all-round performance for hybrid work.",
        short_description="Convertible premium laptop for creators and professionals.",
    ),
    ProductSeed(
        name="ASUS Zenbook 14 OLED",
        category="Laptops",
        brand="ASUS",
        price=Decimal("1299.00"),
        image_paths=("laptops/asus_zenbook_14_oled/front.jpg", "laptops/asus_zenbook_14_oled/gallery_1.jpg"),
        description="The ASUS Zenbook 14 OLED combines portability with an immersive display and efficient performance for everyday productivity.",
        short_description="Compact OLED ultraportable built for work and media consumption.",
    ),
    ProductSeed(
        name="Acer Swift Go 14",
        category="Laptops",
        brand="Acer",
        price=Decimal("999.00"),
        image_paths=("laptops/acer_swift_go_14/front.jpg", "laptops/acer_swift_go_14/gallery_1.jpg"),
        description="The Acer Swift Go 14 is a lightweight laptop designed to handle travel, study, and efficient office workflows.",
        short_description="Affordable ultraportable with a polished, everyday-ready design.",
    ),
    ProductSeed(
        name="Sony WH-1000XM6 Headphones",
        category="Audio Devices",
        brand="Sony",
        price=Decimal("399.00"),
        image_paths=("audio_devices/sony_wh_1000xm6_headphones/front.jpg", "audio_devices/sony_wh_1000xm6_headphones/gallery_1.jpg"),
        description="The Sony WH-1000XM6 Headphones deliver elite noise cancellation, immersive audio, and all-day comfort for travel and focus.",
        short_description="Premium wireless headphones with industry-leading noise cancellation.",
    ),
    ProductSeed(
        name="Apple AirPods Pro (3rd Gen)",
        category="Audio Devices",
        brand="Apple",
        price=Decimal("249.00"),
        image_paths=("audio_devices/apple_airpods_pro_3rd_gen/front.jpg", "audio_devices/apple_airpods_pro_3rd_gen/gallery_1.jpg"),
        description="The Apple AirPods Pro (3rd Gen) combine adaptive audio, secure fit, and dependable Apple ecosystem integration.",
        short_description="Premium earbuds with adaptive audio and seamless Apple pairing.",
    ),
    ProductSeed(
        name="JBL Flip 7 Bluetooth Speaker",
        category="Audio Devices",
        brand="JBL",
        price=Decimal("149.00"),
        image_paths=("audio_devices/jbl_flip_7_bluetooth_speaker/front.jpg", "audio_devices/jbl_flip_7_bluetooth_speaker/gallery_1.jpg"),
        description="The JBL Flip 7 Bluetooth Speaker offers portable sound, rugged durability, and a compact form factor for outdoor listening.",
        short_description="Compact waterproof speaker with clear, immersive sound.",
    ),
    ProductSeed(
        name="Bose QuietComfort Ultra Earbuds",
        category="Audio Devices",
        brand="Bose",
        price=Decimal("299.00"),
        image_paths=("audio_devices/bose_quietcomfort_ultra_earbuds/front.jpg", "audio_devices/bose_quietcomfort_ultra_earbuds/gallery_1.jpg"),
        description="The Bose QuietComfort Ultra Earbuds provide rich, balanced audio and excellent comfort for long listening sessions.",
        short_description="Comfort-first earbuds with premium quiet and rich sound.",
    ),
    ProductSeed(
        name="Soundcore Liberty 4 Pro",
        category="Audio Devices",
        brand="Soundcore",
        price=Decimal("199.00"),
        image_paths=("audio_devices/soundcore_liberty_4_pro/front.jpg", "audio_devices/soundcore_liberty_4_pro/gallery_1.jpg"),
        description="The Soundcore Liberty 4 Pro offers strong active noise cancellation, excellent battery life, and vivid sound at a competitive price.",
        short_description="Feature-rich earbuds with strong ANC and everyday versatility.",
    ),
    ProductSeed(
        name="Marshall Emberton III Speaker",
        category="Audio Devices",
        brand="Marshall",
        price=Decimal("179.00"),
        image_paths=("audio_devices/marshall_emberton_iii_speaker/front.jpg", "audio_devices/marshall_emberton_iii_speaker/gallery_1.jpg"),
        description="The Marshall Emberton III Speaker brings the brand's iconic sound signature into a portable, travel-friendly package.",
        short_description="Portable speaker with bold Marshall-style sound and rugged design.",
    ),
    ProductSeed(
        name="Logitech MX Master 3S Mouse",
        category="Computer Accessories",
        brand="Logitech",
        price=Decimal("99.00"),
        image_paths=("computer_accessories/logitech_mx_master_3s_mouse/front.jpg", "computer_accessories/logitech_mx_master_3s_mouse/gallery_1.jpg"),
        description="The Logitech MX Master 3S Mouse is an ergonomic productivity mouse tuned for multi-device workflows and long workdays.",
        short_description="Ergonomic wireless mouse built for productivity and precision.",
    ),
    ProductSeed(
        name="Logitech MX Keys S Keyboard",
        category="Computer Accessories",
        brand="Logitech",
        price=Decimal("109.00"),
        image_paths=("computer_accessories/logitech_mx_keys_s_keyboard/front.jpg", "computer_accessories/logitech_mx_keys_s_keyboard/gallery_1.jpg"),
        description="The Logitech MX Keys S Keyboard combines quiet switches, excellent ergonomics, and multi-device connectivity.",
        short_description="Low-noise wireless keyboard with premium typing feel.",
    ),
    ProductSeed(
        name="Samsung T9 Portable SSD 1TB",
        category="Computer Accessories",
        brand="Samsung",
        price=Decimal("129.00"),
        image_paths=("computer_accessories/samsung_t9_portable_ssd_1tb/front.jpg", "computer_accessories/samsung_t9_portable_ssd_1tb/gallery_1.jpg"),
        description="The Samsung T9 Portable SSD 1TB offers fast transfer speeds and durable design for creators on the move.",
        short_description="Portable high-speed SSD for backup and on-the-go file transfer.",
    ),
    ProductSeed(
        name="Anker USB-C Hub",
        category="Computer Accessories",
        brand="Anker",
        price=Decimal("79.00"),
        image_paths=("computer_accessories/anker_usb_c_hub/front.jpg", "computer_accessories/anker_usb_c_hub/gallery_1.jpg"),
        description="The Anker USB-C Hub expands a laptop with ports for displays, storage, networking, and charging in one solution.",
        short_description="Compact USB-C hub for desk and travel connectivity.",
    ),
    ProductSeed(
        name="Logitech Brio 4K Webcam",
        category="Computer Accessories",
        brand="Logitech",
        price=Decimal("149.00"),
        image_paths=("computer_accessories/logitech_brio_4k_webcam/front.jpg", "computer_accessories/logitech_brio_4k_webcam/gallery_1.jpg"),
        description="The Logitech Brio 4K Webcam delivers sharp high-definition video and reliable conferencing performance.",
        short_description="4K webcam for crisp video calls and content creation.",
    ),
    ProductSeed(
        name="TP-Link Archer BE550 Wi-Fi Router",
        category="Computer Accessories",
        brand="TP-Link",
        price=Decimal("219.00"),
        image_paths=("computer_accessories/tp_link_archer_be550_wifi_router/front.jpg", "computer_accessories/tp_link_archer_be550_wifi_router/gallery_1.jpg"),
        description="The TP-Link Archer BE550 Wi-Fi Router offers fast, dependable coverage for modern smart homes and home offices.",
        short_description="High-performance Wi-Fi router with modern coverage and speed.",
    ),
    ProductSeed(
        name="Levi's Slim Fit Jeans",
        category="Men's Fashion",
        brand="Levi's",
        price=Decimal("89.00"),
        image_paths=("mens_fashion/levis_slim_fit_jeans/front.jpg", "mens_fashion/levis_slim_fit_jeans/gallery_1.jpg"),
        description="Levi's Slim Fit Jeans combine timeless denim styling with an easy, tailored silhouette for daily wear.",
        short_description="Slim-fit denim staple with a clean, modern silhouette.",
    ),
    ProductSeed(
        name="Nike Sports T-Shirt",
        category="Men's Fashion",
        brand="Nike",
        price=Decimal("59.00"),
        image_paths=("mens_fashion/nike_sports_t_shirt/front.jpg", "mens_fashion/nike_sports_t_shirt/gallery_1.jpg"),
        description="The Nike Sports T-Shirt brings comfort, breathability, and sporty styling into a versatile everyday essential.",
        short_description="Casual athletic tee designed for everyday movement.",
    ),
    ProductSeed(
        name="Adidas Hoodie",
        category="Men's Fashion",
        brand="Adidas",
        price=Decimal("119.00"),
        image_paths=("mens_fashion/adidas_hoodie/front.jpg", "mens_fashion/adidas_hoodie/gallery_1.jpg"),
        description="The Adidas Hoodie delivers soft comfort, a relaxed fit, and easy styling for everyday wear.",
        short_description="Classic hoodie with laid-back comfort and everyday appeal.",
    ),
    ProductSeed(
        name="Tommy Hilfiger Polo Shirt",
        category="Men's Fashion",
        brand="Tommy Hilfiger",
        price=Decimal("79.00"),
        image_paths=("mens_fashion/tommy_hilfiger_polo_shirt/front.jpg", "mens_fashion/tommy_hilfiger_polo_shirt/gallery_1.jpg"),
        description="The Tommy Hilfiger Polo Shirt offers clean, preppy styling and a polished fit that works in smart-casual dressing.",
        short_description="Smart-casual polo shirt with a polished, classic look.",
    ),
    ProductSeed(
        name="Puma Joggers",
        category="Men's Fashion",
        brand="Puma",
        price=Decimal("69.00"),
        image_paths=("mens_fashion/puma_joggers/front.jpg", "mens_fashion/puma_joggers/gallery_1.jpg"),
        description="Puma Joggers are soft, flexible, and designed for comfort across workouts, travel, and narrow downtime.",
        short_description="Relaxed joggers with lightweight comfort and easy styling.",
    ),
    ProductSeed(
        name="Allen Solly Formal Shirt",
        category="Men's Fashion",
        brand="Allen Solly",
        price=Decimal("75.00"),
        image_paths=("mens_fashion/allen_solly_formal_shirt/front.jpg", "mens_fashion/allen_solly_formal_shirt/gallery_1.jpg"),
        description="The Allen Solly Formal Shirt provides a crisp, refined fit ideal for professional and celebratory occasions.",
        short_description="Tailored formal shirt with a polished, professional finish.",
    ),
    ProductSeed(
        name="H&M Floral Midi Dress",
        category="Women's Fashion",
        brand="H&M",
        price=Decimal("79.00"),
        image_paths=("womens_fashion/hm_floral_midi_dress/front.jpg", "womens_fashion/hm_floral_midi_dress/gallery_1.jpg"),
        description="The H&M Floral Midi Dress offers a classic silhouette with a soft, feminine seasonal print.",
        short_description="Floral midi dress styled for effortless day-to-evening wear.",
    ),
    ProductSeed(
        name="Zara Oversized Shirt",
        category="Women's Fashion",
        brand="Zara",
        price=Decimal("89.00"),
        image_paths=("womens_fashion/zara_oversized_shirt/front.jpg", "womens_fashion/zara_oversized_shirt/gallery_1.jpg"),
        description="The Zara Oversized Shirt is a versatile wardrobe layer with relaxed proportions and polished styling.",
        short_description="Relaxed oversized shirt with modern minimalist styling.",
    ),
    ProductSeed(
        name="Levi's High Rise Jeans",
        category="Women's Fashion",
        brand="Levi's",
        price=Decimal("99.00"),
        image_paths=("womens_fashion/levis_high_rise_jeans/front.jpg", "womens_fashion/levis_high_rise_jeans/gallery_1.jpg"),
        description="The Levi's High Rise Jeans bring clean denim tailoring with a flattering, high-rise fit for everyday style.",
        short_description="High-rise denim staple with refined, versatile fit.",
    ),
    ProductSeed(
        name="Only Casual Top",
        category="Women's Fashion",
        brand="Only",
        price=Decimal("49.00"),
        image_paths=("womens_fashion/only_casual_top/front.jpg", "womens_fashion/only_casual_top/gallery_1.jpg"),
        description="The Only Casual Top is a lightweight essential designed for easy layering and day-long comfort.",
        short_description="Easy everyday top with a soft, versatile silhouette.",
    ),
    ProductSeed(
        name="Vero Moda Blazer",
        category="Women's Fashion",
        brand="Vero Moda",
        price=Decimal("129.00"),
        image_paths=("womens_fashion/vero_moda_blazer/front.jpg", "womens_fashion/vero_moda_blazer/gallery_1.jpg"),
        description="The Vero Moda Blazer offers a structured, polished look that elevates both casual and professional outfits.",
        short_description="Structured blazer for a polished, professional finish.",
    ),
    ProductSeed(
        name="Biba Kurta Set",
        category="Women's Fashion",
        brand="Biba",
        price=Decimal("109.00"),
        image_paths=("womens_fashion/biba_kurta_set/front.jpg", "womens_fashion/biba_kurta_set/gallery_1.jpg"),
        description="The Biba Kurta Set blends comfort, traditional detailing, and modern festive styling into one complete outfit.",
        short_description="A versatile kurta set that balances tradition and modern style.",
    ),
    ProductSeed(
        name="Nike Air Max 270",
        category="Footwear",
        brand="Nike",
        price=Decimal("159.00"),
        image_paths=("footwear/nike_air_max_270/front.jpg", "footwear/nike_air_max_270/gallery_1.jpg"),
        description="The Nike Air Max 270 brings bold cushioning and streetwear-driven comfort into a lightweight sneaker silhouette.",
        short_description="Comfort-driven sneaker with a bold, contemporary silhouette.",
    ),
    ProductSeed(
        name="Adidas Ultraboost Light",
        category="Footwear",
        brand="Adidas",
        price=Decimal("179.00"),
        image_paths=("footwear/adidas_ultraboost_light/front.jpg", "footwear/adidas_ultraboost_light/gallery_1.jpg"),
        description="The Adidas Ultraboost Light pairs lightweight energy return with stylish cushioning for everyday running and walking.",
        short_description="Responsive running shoe with lightweight cushioning and support.",
    ),
    ProductSeed(
        name="Puma RS-X Sneakers",
        category="Footwear",
        brand="Puma",
        price=Decimal("119.00"),
        image_paths=("footwear/puma_rs_x_sneakers/front.jpg", "footwear/puma_rs_x_sneakers/gallery_1.jpg"),
        description="The Puma RS-X Sneakers deliver a retro-inspired look with a comfortable, sporty ride for daily use.",
        short_description="Retro-inspired sneakers with day-long comfort.",
    ),
    ProductSeed(
        name="Skechers Go Walk",
        category="Footwear",
        brand="Skechers",
        price=Decimal("89.00"),
        image_paths=("footwear/skechers_go_walk/front.jpg", "footwear/skechers_go_walk/gallery_1.jpg"),
        description="The Skechers Go Walk offers a soft, feather-light feel built for all-day comfort on the move.",
        short_description="Easy-wear walking shoe with lightweight comfort.",
    ),
    ProductSeed(
        name="New Balance 574",
        category="Footwear",
        brand="New Balance",
        price=Decimal("139.00"),
        image_paths=("footwear/new_balance_574/front.jpg", "footwear/new_balance_574/gallery_1.jpg"),
        description="The New Balance 574 is a versatile sneaker model known for dependable support, clean styling, and everyday comfort.",
        short_description="Classic everyday sneaker with dependable cushioning.",
    ),
    ProductSeed(
        name="Clarks Leather Formal Shoes",
        category="Footwear",
        brand="Clarks",
        price=Decimal("149.00"),
        image_paths=("footwear/clarks_leather_formal_shoes/front.jpg", "footwear/clarks_leather_formal_shoes/gallery_1.jpg"),
        description="The Clarks Leather Formal Shoes combine elegant construction with all-day performance for professional settings.",
        short_description="Leather formal shoes with classic office-ready style.",
    ),
    ProductSeed(
        name="Philips Air Fryer",
        category="Home & Kitchen",
        brand="Philips",
        price=Decimal("129.00"),
        image_paths=("home_kitchen/philips_air_fryer/front.jpg", "home_kitchen/philips_air_fryer/gallery_1.jpg"),
        description="The Philips Air Fryer makes healthy, crisp meals easier with fast cooking and low-oil convenience.",
        short_description="Compact air fryer for quick and healthier home cooking.",
    ),
    ProductSeed(
        name="Nespresso Vertuo Coffee Machine",
        category="Home & Kitchen",
        brand="Nespresso",
        price=Decimal("199.00"),
        image_paths=("home_kitchen/nespresso_vertuo_coffee_machine/front.jpg", "home_kitchen/nespresso_vertuo_coffee_machine/gallery_1.jpg"),
        description="The Nespresso Vertuo Coffee Machine brings café-style espresso and coffee drinks into the home with ease.",
        short_description="Coffee machine for high-quality espresso and brewed coffee.",
    ),
    ProductSeed(
        name="Instant Pot Pressure Cooker",
        category="Home & Kitchen",
        brand="Instant Pot",
        price=Decimal("109.00"),
        image_paths=("home_kitchen/instant_pot_pressure_cooker/front.jpg", "home_kitchen/instant_pot_pressure_cooker/gallery_1.jpg"),
        description="The Instant Pot Pressure Cooker is a versatile appliance built to simplify daily meal preparation.",
        short_description="Multi-use cooker that saves time in the kitchen.",
    ),
    ProductSeed(
        name="Prestige Induction Cooktop",
        category="Home & Kitchen",
        brand="Prestige",
        price=Decimal("79.00"),
        image_paths=("home_kitchen/prestige_induction_cooktop/front.jpg", "home_kitchen/prestige_induction_cooktop/gallery_1.jpg"),
        description="The Prestige Induction Cooktop offers modern, energy-efficient cooking with rapid heat control and clean design.",
        short_description="Energy-efficient induction cooktop for modern kitchens.",
    ),
    ProductSeed(
        name="Philips Electric Kettle",
        category="Home & Kitchen",
        brand="Philips",
        price=Decimal("49.00"),
        image_paths=("home_kitchen/philips_electric_kettle/front.jpg", "home_kitchen/philips_electric_kettle/gallery_1.jpg"),
        description="The Philips Electric Kettle makes boiling water faster, safer, and more convenient for busy homes.",
        short_description="Fast-heating electric kettle for everyday kitchen use.",
    ),
    ProductSeed(
        name="LG Microwave Oven",
        category="Home & Kitchen",
        brand="LG",
        price=Decimal("149.00"),
        image_paths=("home_kitchen/lg_microwave_oven/front.jpg", "home_kitchen/lg_microwave_oven/gallery_1.jpg"),
        description="The LG Microwave Oven offers dependable performance and versatile cooking options in a streamlined countertop design.",
        short_description="Countertop microwave oven with reliable everyday performance.",
    ),
    ProductSeed(
        name="CeraVe Foaming Cleanser",
        category="Beauty & Personal Care",
        brand="CeraVe",
        price=Decimal("24.00"),
        image_paths=("beauty_personal_care/cerave_foaming_cleanser/front.jpg", "beauty_personal_care/cerave_foaming_cleanser/gallery_1.jpg"),
        description="The CeraVe Foaming Cleanser gently removes excess oil and impurities while keeping skin comfort in balance.",
        short_description="Daily cleanser for balanced, refreshed skin.",
    ),
    ProductSeed(
        name="La Roche-Posay Sunscreen SPF 50",
        category="Beauty & Personal Care",
        brand="La Roche-Posay",
        price=Decimal("33.00"),
        image_paths=("beauty_personal_care/la_roche_posay_sunscreen_spf_50/front.jpg", "beauty_personal_care/la_roche_posay_sunscreen_spf_50/gallery_1.jpg"),
        description="The La Roche-Posay Sunscreen SPF 50 provides reliable broad-spectrum sun protection with a lightweight finish.",
        short_description="Daily SPF protection with a lightweight, wearable finish.",
    ),
    ProductSeed(
        name="L'Oréal Paris Vitamin C Serum",
        category="Beauty & Personal Care",
        brand="L'Oréal Paris",
        price=Decimal("39.00"),
        image_paths=("beauty_personal_care/loral_paris_vitamin_c_serum/front.jpg", "beauty_personal_care/loral_paris_vitamin_c_serum/gallery_1.jpg"),
        description="The L'Oréal Paris Vitamin C Serum helps brighten the complexion with a smooth, glow-supporting daily formula.",
        short_description="Radiance-focused serum with daily brightening support.",
    ),
    ProductSeed(
        name="Philips OneBlade Trimmer",
        category="Beauty & Personal Care",
        brand="Philips",
        price=Decimal("34.00"),
        image_paths=("beauty_personal_care/philips_oneblade_trimmer/front.jpg", "beauty_personal_care/philips_oneblade_trimmer/gallery_1.jpg"),
        description="The Philips OneBlade Trimmer offers flexible grooming performance in a sleek, easy-to-use design.",
        short_description="Travel-friendly grooming trimmer for quick daily maintenance.",
    ),
    ProductSeed(
        name="Oral-B Electric Toothbrush",
        category="Beauty & Personal Care",
        brand="Oral-B",
        price=Decimal("44.00"),
        image_paths=("beauty_personal_care/oral_b_electric_toothbrush/front.jpg", "beauty_personal_care/oral_b_electric_toothbrush/gallery_1.jpg"),
        description="The Oral-B Electric Toothbrush is built for efficient plaque removal and a more complete daily brushing routine.",
        short_description="Electric toothbrush for a cleaner, more polished brushing routine.",
    ),
    ProductSeed(
        name="Nivea Soft Moisturizing Cream",
        category="Beauty & Personal Care",
        brand="Nivea",
        price=Decimal("19.00"),
        image_paths=("beauty_personal_care/nivea_soft_moisturizing_cream/front.jpg", "beauty_personal_care/nivea_soft_moisturizing_cream/gallery_1.jpg"),
        description="The Nivea Soft Moisturizing Cream nourishes and softens the skin with a light, easy-to-apply daily formula.",
        short_description="Daily moisturizer for soft, nourished skin.",
    ),
    ProductSeed(
        name="American Tourister Backpack",
        category="Bags & Travel",
        brand="American Tourister",
        price=Decimal("89.00"),
        image_paths=("bags_travel/american_tourister_backpack/front.jpg", "bags_travel/american_tourister_backpack/gallery_1.jpg"),
        description="The American Tourister Backpack is a practical carry solution with durable construction and organized storage.",
        short_description="Travel-ready backpack with durable construction and storage utility.",
    ),
    ProductSeed(
        name="Samsonite Cabin Suitcase",
        category="Bags & Travel",
        brand="Samsonite",
        price=Decimal("189.00"),
        image_paths=("bags_travel/samsonite_cabin_suitcase/front.jpg", "bags_travel/samsonite_cabin_suitcase/gallery_1.jpg"),
        description="The Samsonite Cabin Suitcase combines refined design, reliable protection, and compact cabin-friendly dimensions.",
        short_description="Stylish cabin suitcase for short trips and frequent flyers.",
    ),
    ProductSeed(
        name="Wildcraft Trekking Backpack",
        category="Bags & Travel",
        brand="Wildcraft",
        price=Decimal("99.00"),
        image_paths=("bags_travel/wildcraft_trekking_backpack/front.jpg", "bags_travel/wildcraft_trekking_backpack/gallery_1.jpg"),
        description="The Wildcraft Trekking Backpack is built for outdoor excursions with the space and comfort needed for longer treks.",
        short_description="Durable trekking backpack made for outdoor adventures.",
    ),
    ProductSeed(
        name="Skybags Laptop Backpack",
        category="Bags & Travel",
        brand="Skybags",
        price=Decimal("79.00"),
        image_paths=("bags_travel/skybags_laptop_backpack/front.jpg", "bags_travel/skybags_laptop_backpack/gallery_1.jpg"),
        description="The Skybags Laptop Backpack keeps work essentials organized while remaining comfortable for everyday commute.",
        short_description="Practical laptop backpack built for work and travel.",
    ),
    ProductSeed(
        name="Tommy Hilfiger Messenger Bag",
        category="Bags & Travel",
        brand="Tommy Hilfiger",
        price=Decimal("99.00"),
        image_paths=("bags_travel/tommy_hilfiger_messenger_bag/front.jpg", "bags_travel/tommy_hilfiger_messenger_bag/gallery_1.jpg"),
        description="The Tommy Hilfiger Messenger Bag offers a structured, polished look suitable for office, travel, and casual weekends.",
        short_description="Clean messenger bag with polished, everyday utility.",
    ),
    ProductSeed(
        name="Nike Gym Duffel Bag",
        category="Bags & Travel",
        brand="Nike",
        price=Decimal("94.00"),
        image_paths=("bags_travel/nike_gym_duffel_bag/front.jpg", "bags_travel/nike_gym_duffel_bag/gallery_1.jpg"),
        description="The Nike Gym Duffel Bag is a dependable carry solution for workouts, travel, and weekend getaways.",
        short_description="Spacious duffel bag built for gym and travel use.",
    ),
]

IMAGE_ROOT = Path("products")


def get_catalog() -> Dict[str, object]:
    """Return the static catalog payload used by seed_data.

    Keeping this in a separate module makes the command import-driven and
    keeps the data source isolated from the orchestration logic.
    """

    return {
        "categories": CATEGORY_NAMES,
        "brands": BRANDS,
        "products": PRODUCTS,
        "image_root": IMAGE_ROOT,
    }
