# Generated by Django 5.0.6 on 2026-10-01 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_siteconfiguration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentlyViewedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recently_viewed_by",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recently_viewed_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "products_recently_viewed_product",
                "ordering": ["-viewed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-viewed_at"], name="recent_user_viewed_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recentlyviewedproduct",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_recent_view_user_product"
            ),
        ),
    ]
